##########################################
###### StormOS Manjaro XFCE Profile ######
##########################################

# possible values: openrc,systemd
initsys="systemd"

displaymanager="lightdm"

################ install ################

kernel="linux612"

# efi_boot_loader="grub"

# plymouth_theme=stormos-plymouth

# start_systemd=('bluetooth' 'cronie' 'ModemManager' 'NetworkManager' 'tlp' 'tlp-sleep')

################# livecd #################

hostname="stormos-manjaro"

username="stormos"

password="stormos"

addgroups="video,audio,power,disk,storage,optical,network,lp,scanner,wheel"

# start_systemd_live=('livecd' 'mhwd-live' 'pacman-init' 'pacman-boot')
