general.live_config_reload = true

[colors.bright]
black = "0x6272A4"
blue = "0xD6ACFF"
cyan = "0xA4FFFF"
green = "0x69FF94"
magenta = "0xFF92DF"
red = "0xFF6E6E"
white = "0xFFFFFF"
yellow = "0xFFFFA5"

[colors.normal]
black = "0x282A36"
blue = "0xBD93F9"
cyan = "0x8BE9FD"
green = "0x50FA7B"
magenta = "0xFF79C6"
red = "0xFF5555"
white = "0xBFBFBF"
yellow = "0xF1FA8C"

[colors.primary]
background = "0x1E2127"
foreground = "0xF8F8F2"

[font]
size = 14

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.bold_italic]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 1

[window]
dynamic_padding = true
opacity = 0.85
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[scrolling]
history = 5000

[window.padding]
x = 6
y = 6

[env]
TERM = "xterm-256color"