# StormOS Foot configuration
[main]
font=JetBrains Mono:size=11
pad=8x8
initial-window-size-pixels=1100x700
initial-window-mode=windowed
term=xterm-256color
dpi-aware=yes
resize-delay-ms=100

[colors]
alpha=0.88
background=11131a
foreground=e9ecf2
regular0=171a23
regular1=f87171
regular2=86efac
regular3=fde68a
regular4=93c5fd
regular5=d8b4fe
regular6=67e8f9
regular7=e5e7eb
bright0=4b5563
bright1=fca5a5
bright2=bbf7d0
bright3=fef3c7
bright4=bfdbfe
bright5=e9d5ff
bright6=a5f3fc
bright7=f9fafb

[scrollback]
lines=10000

[key-bindings]
clipboard-copy=Control+Shift+c
clipboard-paste=Control+Shift+v
