# StormOS XFCE Calamares configuration
# Syntax is YAML 1.2
---

modules-search: [ local ]

instances:
- id: drivers
  module: netinstall
  config: net_drivers.conf
- id: software
  module: netinstall
  config: net_software.conf
- id: first
  module: shellprocess
  config: shellprocess-first.conf
- id: cyberxero
  module: shellprocess
  config: shellprocess-cyberxero.conf
- id: mainline
  module: initcpio
  config: initcpio-linux.conf
- id: lts
  module: initcpio
  config: initcpio-linux-lts.conf
- id: zen
  module: initcpio
  config: initcpio-linux-zen.conf

sequence:
- show:
  - welcome
  - netinstall@drivers
  - netinstall@software
  - locale
  - keyboard
  - partition
  - users
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - luksbootkeyfile
  - luksopenswaphookcfg
  - shellprocess@first
  - netinstall@software
  - netinstall@drivers
  - initcpiocfg
  - initcpio@mainline
  - initcpio@lts
  - initcpio@zen
  - users
  - removeuser
  - displaymanager
  - networkcfg
  - hwclock
  - services-systemd
  - packages
  - grubcfg
  - bootloader
  - shellprocess
  - shellprocess@cyberxero
  - preservefiles
  - umount
- show:
  - finished

branding: Storm
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
