---
# StormOS GRUB defaults

overwrite: false
prefer_grub_d: false
keep_distributor: false
kernel_params: [ quiet, splash, loglevel=3, nowatchdog ]

defaults:
  GRUB_TIMEOUT: 5
  GRUB_DEFAULT: 0
  GRUB_DISABLE_RECOVERY: true
  GRUB_DISABLE_OS_PROBER: "false"
  GRUB_TERMINAL_OUTPUT: console
  GRUB_CMDLINE_LINUX_DEFAULT: "quiet splash loglevel=3 nowatchdog"
  GRUB_THEME: /usr/share/grub/themes/stormos/theme.txt
  GRUB_SAVEDEFAULT: "false"
