[Icon Theme]
Name=StormOS-icons
Comment=StormOS blue colored icon theme
Inherits=Qogir-dark,hicolor
FollowsColorScheme=false

Example=folder
DisplayDepth=32

DesktopDefault=48
DesktopSizes=16,22,24,32,48,64
ToolbarDefault=22
ToolbarSizes=16,22,24,32,48
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32,48
SmallDefault=16
SmallSizes=16,22,24,32,48
PanelDefault=48
PanelSizes=16,22,24,32,48,64
DialogDefault=48
DialogSizes=16,22,24,32,48,64

Directories=scalable/places,scalable/apps,scalable/mimetypes,scalable/devices,scalable/status,scalable/actions,16/apps,16/places,22/apps,22/places,24/apps,24/places,32/apps,32/places,48/apps,48/places,64/apps,64/places,96/apps,96/places,128/apps,128/places

[scalable/places]
Context=Places
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/apps]
Context=Applications
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Context=Actions
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[16/apps]
Context=Applications
Size=16
Type=Scalable

[16/places]
Context=Places
Size=16
Type=Scalable

[22/apps]
Context=Applications
Size=22
Type=Scalable

[22/places]
Context=Places
Size=22
Type=Scalable

[24/apps]
Context=Applications
Size=24
Type=Scalable

[24/places]
Context=Places
Size=24
Type=Scalable

[32/apps]
Context=Applications
Size=32
Type=Scalable

[32/places]
Context=Places
Size=32
Type=Scalable

[48/apps]
Context=Applications
Size=48
Type=Scalable

[48/places]
Context=Places
Size=48
Type=Scalable

[64/apps]
Context=Applications
Size=64
Type=Scalable

[64/places]
Context=Places
Size=64
Type=Scalable

[96/apps]
Context=Applications
Size=96
Type=Scalable

[96/places]
Context=Places
Size=96
Type=Scalable

[128/apps]
Context=Applications
Size=128
Type=Scalable

[128/places]
Context=Places
Size=128
Type=Scalable
