[Icon Theme]
Name=StormOS-icons
Comment=StormOS blue icon overrides
Inherits=Qogir-dark,hicolor
FollowsColorScheme=false

Example=folder
DisplayDepth=32

DesktopDefault=48
DesktopSizes=16,22,24,32,48
ToolbarDefault=22
ToolbarSizes=16,22,24,32
MainToolbarDefault=22
MainToolbarSizes=16,22,24,32
SmallDefault=16
SmallSizes=16,22,24,32
PanelDefault=48
PanelSizes=16,22,24,32,48
DialogDefault=48
DialogSizes=16,22,24,32,48

Directories=16/apps,16/places,16/status,22/apps,22/places,22/status,48/apps,48/places,48/status,scalable/apps,scalable/places,scalable/status,scalable/mimetypes,scalable/devices,scalable/actions

[16/apps]
Context=Applications
Size=16
Type=Fixed

[16/places]
Context=Places
Size=16
Type=Fixed

[16/status]
Context=Status
Size=16
Type=Fixed

[22/apps]
Context=Applications
Size=22
Type=Fixed

[22/places]
Context=Places
Size=22
Type=Fixed

[22/status]
Context=Status
Size=22
Type=Fixed

[48/apps]
Context=Applications
Size=48
Type=Fixed

[48/places]
Context=Places
Size=48
Type=Fixed

[48/status]
Context=Status
Size=48
Type=Fixed

[scalable/apps]
Context=Applications
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/status]
Context=Status
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/devices]
Context=Devices
Size=64
MinSize=16
MaxSize=512
Type=Scalable

[scalable/actions]
Context=Actions
Size=64
MinSize=16
MaxSize=512
Type=Scalable
