---

dontChroot: false
timeout: 999

script:
    - command: "rm -rf /etc/pacman.d/gnupg"
    - command: "pacman-key --init"
    - command: "pacman-key --populate archlinux"
    - command: "pacman -Sy --noconfirm archlinux-keyring"
    - command: "pacman-key --populate archlinux"
    - command: "systemctl disable pacman-init.service"
    - command: "rm -f /etc/mkinitcpio.d/linux.preset /etc/mkinitcpio.d/linux-lts.preset /etc/mkinitcpio.d/linux-zen.preset"
    - command: "install -Dm644 /etc/stormos/mkinitcpio-presets/linux.preset /etc/mkinitcpio.d/linux.preset"
    - command: "install -Dm644 /etc/stormos/mkinitcpio-presets/linux-lts.preset /etc/mkinitcpio.d/linux-lts.preset"
    - command: "install -Dm644 /etc/stormos/mkinitcpio-presets/linux-zen.preset /etc/mkinitcpio.d/linux-zen.preset"

