[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-slick-greeter
user-session=xfce
allow-user-switching=true
autologin-guest=false
autologin-user-timeout=0

[XDMCPServer]

[VNCServer]
