[greeter]
theme-name=Arc-BLACK-ICE
icon-theme-name=Qogir
background=/usr/share/backgrounds/stormos-wallpaper.png
font-name=Inter 11
clock-format=%A, %H:%M %p
position=50%,center 50%,center
screensaver-timeout=0
xft-antialias=true
xft-dpi=96
xft-hintstyle=slight
xft-rgba=rgb
user-background=false
