[LightDM]
run-directory=/run/lightdm

[Seat:*]
greeter-session=lightdm-slick-greeter
user-session=stormos-desktop
session-wrapper=/etc/lightdm/Xsession
allow-user-switching=true
autologin-guest=false
autologin-user-timeout=0
autologin-session=stormos-desktop

[Greeter]
background=/usr/share/backgrounds/stormos-wallpaper.png
logo=/usr/share/pixmaps/stormos/menubutton.png
theme-name=Arc-BLACK-ICE
icon-theme-name=Qogir
font-name=Inter 11

[XDMCPServer]

[VNCServer]
