[Greeter]
background=/usr/share/backgrounds/stormos-wallpaper.png
logo=/usr/share/pixmaps/stormos/menubutton.png
theme-name=StormOS-GTK
icon-theme-name=Qogir
font-name=Inter 11
enable-hidpi=auto
draw-user-background=false
draw-grid=false
blur-radius=10
blur-saturation=1.0
