displaymanagers:
  - sddm
  - lightdm
  - gdm
  - lxdm
basicSetup: false
lightdm:
  preferred_greeters: ["lightdm-greeter.desktop", "slick-greeter.desktop"]
sddm:
  configuration_file: "/etc/sddm.conf"
