---
# StormOS KDE services

units:
  - name: NetworkManager.service
    action: enable
    mandatory: true
  - name: plasmalogin.service
    action: enable
    mandatory: true
  - name: bluetooth.service
    action: enable
    mandatory: true
  - name: sshd.service
    action: enable
    mandatory: true
  - name: fstrim.timer
    action: enable
    mandatory: true
  - name: pacman-init.service
    action: disable
    mandatory: false
