---

dontChroot: false
timeout: 999

script:
    - command: "rm -rf /etc/pacman.d/gnupg"
    - command: "pacman-key --init"
    - command: "pacman-key --populate archlinux"
    - command: "pacman -Sy --noconfirm archlinux-keyring"
    - command: "pacman-key --populate archlinux"
    - command: "systemctl disable pacman-init.service"

